/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package eleccionesPresidenciales;

/**
 *
 * @author PeterZipek
 */
public class SegundaVuelta extends javax.swing.JFrame {

    /**
     * Creates new form SegundaVuelta
     */
    public SegundaVuelta() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jFrame1 = new javax.swing.JFrame();
        jPanelPrincipal = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnPiñera = new javax.swing.JButton();
        btnGuillier = new javax.swing.JButton();
        btnBlancos = new javax.swing.JButton();
        btnNulos = new javax.swing.JButton();
        lblOpcion1 = new javax.swing.JLabel();
        lblOpcion2 = new javax.swing.JLabel();
        lblOpcion3 = new javax.swing.JLabel();
        lblOpcion4 = new javax.swing.JLabel();
        btnDescontarGuillier = new javax.swing.JButton();
        btnDescontarPiñera = new javax.swing.JButton();
        btnDescontarNulos = new javax.swing.JButton();
        btnDescontarBlancos = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblOpcionR1 = new javax.swing.JLabel();
        lblOpcionR2 = new javax.swing.JLabel();
        lblOpcionR3 = new javax.swing.JLabel();
        lblOpcionR4 = new javax.swing.JLabel();
        lblTotalGuillier = new javax.swing.JLabel();
        lblTotalPiñera = new javax.swing.JLabel();
        lblTotalNulos = new javax.swing.JLabel();
        lblTotalBlancos = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        lblTotalVotos = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Segunda Vuelta 2017");
        setBackground(new java.awt.Color(0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Adobe Arabic", 1, 10)); // NOI18N
        setForeground(java.awt.Color.black);
        setMinimumSize(new java.awt.Dimension(1366, 700));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);

        jPanelPrincipal.setBackground(new java.awt.Color(0, 153, 153));
        jPanelPrincipal.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Elecciones Presidenciales 2017", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Serif", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanelPrincipal.setToolTipText("");
        jPanelPrincipal.setName("Elecciones"); // NOI18N
        jPanelPrincipal.setPreferredSize(new java.awt.Dimension(996, 682));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Votar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(470, 470));

        btnPiñera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/piñera.jpg"))); // NOI18N
        btnPiñera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPiñeraActionPerformed(evt);
            }
        });

        btnGuillier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/guillier.jpg"))); // NOI18N
        btnGuillier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuillierActionPerformed(evt);
            }
        });

        btnBlancos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/blanco.jpeg"))); // NOI18N
        btnBlancos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBlancosActionPerformed(evt);
            }
        });

        btnNulos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/nulo.jpg"))); // NOI18N
        btnNulos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNulosActionPerformed(evt);
            }
        });

        lblOpcion1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblOpcion1.setForeground(new java.awt.Color(255, 255, 255));
        lblOpcion1.setText("Sebastian Piñera");

        lblOpcion2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblOpcion2.setForeground(new java.awt.Color(255, 255, 255));
        lblOpcion2.setText("Alejandro Guillier");

        lblOpcion3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblOpcion3.setForeground(new java.awt.Color(255, 255, 255));
        lblOpcion3.setText("Nulos");

        lblOpcion4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblOpcion4.setForeground(new java.awt.Color(255, 255, 255));
        lblOpcion4.setText("Blancos");

        btnDescontarGuillier.setBackground(new java.awt.Color(255, 102, 102));
        btnDescontarGuillier.setForeground(new java.awt.Color(255, 255, 255));
        btnDescontarGuillier.setText("Descontar a Guillier");
        btnDescontarGuillier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDescontarGuillierActionPerformed(evt);
            }
        });

        btnDescontarPiñera.setBackground(new java.awt.Color(255, 102, 102));
        btnDescontarPiñera.setForeground(new java.awt.Color(255, 255, 255));
        btnDescontarPiñera.setText("Descontar a Piñera");
        btnDescontarPiñera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDescontarPiñeraActionPerformed(evt);
            }
        });

        btnDescontarNulos.setBackground(new java.awt.Color(255, 102, 102));
        btnDescontarNulos.setForeground(new java.awt.Color(255, 255, 255));
        btnDescontarNulos.setText("Descontar un Nulo");
        btnDescontarNulos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDescontarNulosActionPerformed(evt);
            }
        });

        btnDescontarBlancos.setBackground(new java.awt.Color(255, 102, 102));
        btnDescontarBlancos.setForeground(new java.awt.Color(255, 255, 255));
        btnDescontarBlancos.setText("Descontar un Blanco");
        btnDescontarBlancos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDescontarBlancosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(btnDescontarPiñera)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDescontarGuillier)
                .addGap(33, 33, 33))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(lblOpcion3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblOpcion4)
                .addGap(65, 65, 65))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnPiñera)
                        .addGap(79, 79, 79)
                        .addComponent(btnGuillier))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(lblOpcion1)
                        .addGap(104, 104, 104)
                        .addComponent(lblOpcion2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnNulos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBlancos)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(btnDescontarNulos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDescontarBlancos)
                .addGap(32, 32, 32))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOpcion1)
                    .addComponent(lblOpcion2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPiñera, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuillier, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnDescontarGuillier, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDescontarPiñera, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOpcion3)
                    .addComponent(lblOpcion4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNulos, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBlancos, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDescontarNulos, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDescontarBlancos, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68))
        );

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Resultados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPanel2.setPreferredSize(new java.awt.Dimension(470, 470));

        lblOpcionR1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblOpcionR1.setForeground(new java.awt.Color(255, 255, 255));
        lblOpcionR1.setText("Sebastian Piñera  :");

        lblOpcionR2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblOpcionR2.setForeground(new java.awt.Color(255, 255, 255));
        lblOpcionR2.setText("Alejandro Guillier :");

        lblOpcionR3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblOpcionR3.setForeground(new java.awt.Color(255, 255, 255));
        lblOpcionR3.setText("Nulos :");

        lblOpcionR4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblOpcionR4.setForeground(new java.awt.Color(255, 255, 255));
        lblOpcionR4.setText("Blancos :");

        lblTotalGuillier.setBackground(new java.awt.Color(213, 255, 48));
        lblTotalGuillier.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        lblTotalGuillier.setForeground(new java.awt.Color(255, 255, 204));
        lblTotalGuillier.setText("0");

        lblTotalPiñera.setBackground(new java.awt.Color(213, 255, 48));
        lblTotalPiñera.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        lblTotalPiñera.setForeground(new java.awt.Color(255, 255, 204));
        lblTotalPiñera.setText("0");

        lblTotalNulos.setBackground(new java.awt.Color(213, 255, 48));
        lblTotalNulos.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        lblTotalNulos.setForeground(new java.awt.Color(255, 255, 204));
        lblTotalNulos.setText("0");

        lblTotalBlancos.setBackground(new java.awt.Color(213, 255, 48));
        lblTotalBlancos.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        lblTotalBlancos.setForeground(new java.awt.Color(255, 255, 204));
        lblTotalBlancos.setText("0");

        lblTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(255, 255, 255));
        lblTotal.setText("Total de Votos : ");

        lblTotalVotos.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTotalVotos.setForeground(new java.awt.Color(0, 204, 102));
        lblTotalVotos.setText("0");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblOpcionR2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTotalGuillier, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblOpcionR3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTotalNulos, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(lblOpcionR4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTotalBlancos, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblOpcionR1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTotalPiñera, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTotal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTotalVotos)
                .addGap(53, 53, 53))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOpcionR1)
                    .addComponent(lblTotalPiñera))
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOpcionR2)
                    .addComponent(lblTotalGuillier))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOpcionR3)
                    .addComponent(lblTotalNulos))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOpcionR4)
                    .addComponent(lblTotalBlancos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotal)
                    .addComponent(lblTotalVotos))
                .addGap(22, 22, 22))
        );

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Desarrollado por Pedro Araya | Zipek Tecnología");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(451, 451, 451)
                .addComponent(jLabel1)
                .addContainerGap(271, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelPrincipalLayout = new javax.swing.GroupLayout(jPanelPrincipal);
        jPanelPrincipal.setLayout(jPanelPrincipalLayout);
        jPanelPrincipalLayout.setHorizontalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE)
                        .addContainerGap())))
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelPrincipalLayout.setVerticalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 558, Short.MAX_VALUE))
                .addGap(29, 29, 29)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 722, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private int contarPiñera =0; 
    
    private int contarGuillier =0; 
    
    private int contarBlancos =0; 
    
    private int contarNulos =0; 

    
    public int contarTotal =0;
            
 
    
    private void btnPiñeraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPiñeraActionPerformed
     
       contarPiñera++;
       contarTotal++;
       
       String voto = String.valueOf(contarPiñera);
       lblTotalPiñera.setText(voto); 
       
       String total=String.valueOf(contarTotal);
       lblTotalVotos.setText(total);
    }//GEN-LAST:event_btnPiñeraActionPerformed

    private void btnGuillierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuillierActionPerformed
       contarGuillier++;
       contarTotal++;
       
       String voto = String.valueOf(contarGuillier);
       lblTotalGuillier.setText(voto); 
       
       String total=String.valueOf(contarTotal);
       lblTotalVotos.setText(total);
     
    }//GEN-LAST:event_btnGuillierActionPerformed

    private void btnNulosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNulosActionPerformed
       contarNulos++;
       contarTotal++;
       
       String voto = String.valueOf(contarNulos);
       lblTotalNulos.setText(voto); 
       
       String total=String.valueOf(contarTotal);
       lblTotalVotos.setText(total);
       
    }//GEN-LAST:event_btnNulosActionPerformed

    private void btnBlancosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBlancosActionPerformed
        contarBlancos++;
        contarTotal++;
        
       String voto = String.valueOf(contarBlancos);
       lblTotalBlancos.setText(voto);
       
        String total=String.valueOf(contarTotal);
       lblTotalVotos.setText(total);
    }//GEN-LAST:event_btnBlancosActionPerformed

    private void btnDescontarPiñeraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDescontarPiñeraActionPerformed
       
       contarPiñera--;
       contarTotal--;
       
       String voto = String.valueOf(contarPiñera);
       lblTotalPiñera.setText(voto); 
       
       String total=String.valueOf(contarTotal);
       lblTotalVotos.setText(total);
    }//GEN-LAST:event_btnDescontarPiñeraActionPerformed

    private void btnDescontarGuillierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDescontarGuillierActionPerformed
       contarGuillier--;
       contarTotal--;
       
       String voto = String.valueOf(contarGuillier);
       lblTotalGuillier.setText(voto); 
       
       String total=String.valueOf(contarTotal);
       lblTotalVotos.setText(total);
    }//GEN-LAST:event_btnDescontarGuillierActionPerformed

    private void btnDescontarNulosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDescontarNulosActionPerformed
       contarNulos--;
       contarTotal--;
       
       String voto = String.valueOf(contarNulos);
       lblTotalNulos.setText(voto); 
       
       String total=String.valueOf(contarTotal);
       lblTotalVotos.setText(total);
       
    }//GEN-LAST:event_btnDescontarNulosActionPerformed

    private void btnDescontarBlancosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDescontarBlancosActionPerformed
            contarBlancos--;
        contarTotal--;
        
       String voto = String.valueOf(contarBlancos);
       lblTotalBlancos.setText(voto);
       
        String total=String.valueOf(contarTotal);
       lblTotalVotos.setText(total);
    }//GEN-LAST:event_btnDescontarBlancosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SegundaVuelta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SegundaVuelta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SegundaVuelta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SegundaVuelta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SegundaVuelta().setVisible(true);
              
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBlancos;
    private javax.swing.JButton btnDescontarBlancos;
    private javax.swing.JButton btnDescontarGuillier;
    private javax.swing.JButton btnDescontarNulos;
    private javax.swing.JButton btnDescontarPiñera;
    private javax.swing.JButton btnGuillier;
    private javax.swing.JButton btnNulos;
    private javax.swing.JButton btnPiñera;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelPrincipal;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblOpcion1;
    private javax.swing.JLabel lblOpcion2;
    private javax.swing.JLabel lblOpcion3;
    private javax.swing.JLabel lblOpcion4;
    private javax.swing.JLabel lblOpcionR1;
    private javax.swing.JLabel lblOpcionR2;
    private javax.swing.JLabel lblOpcionR3;
    private javax.swing.JLabel lblOpcionR4;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblTotalBlancos;
    private javax.swing.JLabel lblTotalGuillier;
    private javax.swing.JLabel lblTotalNulos;
    private javax.swing.JLabel lblTotalPiñera;
    private javax.swing.JLabel lblTotalVotos;
    // End of variables declaration//GEN-END:variables
}
